language: python

dist: trusty
sudo: required

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
  - "3.6"
  - "3.6-dev"
  - "nightly"

matrix:
  allow_failures:
    - python: "3.5-dev"
    - python: "3.6-dev"
    - python: "nightly"

before_script:
  - make install_deps

script:
  - uname -a
  - pytest --version
  - python -V
  - make test